ALPHA = 0.9
GAMMA = 0.5
MAX_EPISODES = 2000

INITIAL_ENERGY_J = 100.0
TX_ENERGY_J = 0.00066
RX_ENERGY_J = 0.000395
LOW_ENERGY_THRESHOLD_J = 20.0

PACKET_SIZE_BYTES = 512
TX_ENERGY_PER_BYTE_J = TX_ENERGY_J / PACKET_SIZE_BYTES
RX_ENERGY_PER_BYTE_J = RX_ENERGY_J / PACKET_SIZE_BYTES
QUEUE_CAPACITY = 100
BANDWIDTH_BPS = 20_000_000
TIME_STEP_SECONDS = 0.01
MAX_TRAINING_STEPS = 50

HELLO_PACKET_BYTES = 40
Q_UPDATE_PACKET_BYTES_QQAR = 24
Q_UPDATE_PACKET_BYTES_PLAIN = 16
LINK_FEEDBACK_PACKET_BYTES = 12

PRIORITY_PROFILE = (
    (0.05, "High+", 1.0),
    (0.15, "High", 2.0),
    (0.40, "Med", 5.0),
    (1.00, "Low", 10.0),
)

TRAFFIC_LOAD_THRESHOLD = 0.5

LABEL_QQAR_2HOP = "QQAR paper algorithm (2-hop discovery)"
LABEL_QQAR_1HOP = "QQAR with 1-hop discovery"
LABEL_BASELINE_Q = "Plain Q-learning baseline (1-hop)"

AGENT_LABELS = (
    LABEL_QQAR_2HOP,
    LABEL_QQAR_1HOP,
    LABEL_BASELINE_Q,
)
